- hosts: localtest
  sudo: yes
  vars:
    mysql_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35386562643061643461356538646237323336386434323062656165623635386162383438393132
          6564366133346434633334346337636333396637626639390a336338663464356334613665656135
          39376633306366623730306565396331343630643962323133653734333530666236656138356162
          3965323634353330370a316161346631646665346134613865346635353863313463656233393638
          3231
    commuter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63353137353631613031633537663934353833616430313239386661383436343464386263633862
          3534626132303639343165373431363732306563363962620a333163653963303163643732333932
          32323764363932343636306434323334343838653566636438363832383037613164306439323731
          6439326139363733360a373237643037393739643733306663313635316535363362323832643762
          6537
    base_dir: /home/vagrant
  tasks:
  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    sudo: yes
    with_items:
    - python-mysqldb
    - mysql-server
    - git
  #- name: copy cnf
  #  copy: src=.my.cnf dest=~/.my.cnf owner=ubuntu mode=0644
  #  sudo: yes
  - name: Start the MySQL service
    sudo: yes
    service:
      name: mysql
      state: started
      enabled: true
  - name: update mysql root password for all root accounts
    sudo: yes
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
  - name: copy schema
    template: src=../resources/database/base.sql dest=/tmp/base.sql
  - name: create db
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: commute
      state: present
      target: /tmp/base.sql
  - name: create test db
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: test_commute
      state: present
      target: /tmp/base.sql
  - name: rm base.sql
    command: rm /tmp/base.sql
  - name: Install list of packages
    apt: name="{{item}}" state=installed
    with_items:
       - python3
       - python3-pip
       - cython
  - name: Install virtualenv
    command: pip3 install virtualenv
  - name: Create virtualenv
    command: virtualenv {{ base_dir }}/venvs/commute_venv -p python3.4 creates="{{ base_dir }}/venvs/commute_venv"
  - name: copy requirements
    template: src=../requirements.txt dest=/tmp/requirements.txt
  - pip:
      requirements: /tmp/requirements.txt
      virtualenv: "{{ base_dir }}/venvs/commute_venv"
  - git:
      repo: https://github.com/jbremson/scratch.git
      dest: "{{ base_dir }}/scratch"
  - name: copy special config data
    template: src=../src/secret_config.py dest={{ base_dir }}/scratch/src
  - name: Install libs to venv
    command: "{{ base_dir }}/venvs/commute_venv/bin/python3 setup.py install"
    args:
      chdir: "{{ base_dir }}/scratch"
  - mysql_user:
      name: commuter
      config_file: ~/.my.cnf
      password: "{{ commuter_password }}"
      priv: "commute.*:SELECT,INSERT,UPDATE,DELETE"
  - cron:
      name: run scraper
      minute: "0"
      hour: "0,2,4,5,6,7,8,9,10,11,13,15,16,17,18,19,20,21,22"
      job: "{{ base_dir}}/venvs/commute_venv/bin/python3 {{base_dir}}/scratch/src/scrape.py"


