- hosts: localtest
  sudo: yes
  vars:
    mysql_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35386562643061643461356538646237323336386434323062656165623635386162383438393132
          6564366133346434633334346337636333396637626639390a336338663464356334613665656135
          39376633306366623730306565396331343630643962323133653734333530666236656138356162
          3965323634353330370a316161346631646665346134613865346635353863313463656233393638
          3231


  tasks:
  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    sudo: yes
    with_items:
    - python-mysqldb
    - mysql-server
    - git
  #- name: copy cnf
  #  copy: src=.my.cnf dest=~/.my.cnf owner=ubuntu mode=0644
  #  sudo: yes
  - name: Start the MySQL service
    sudo: yes
    service:
      name: mysql
      state: started
      enabled: true
  - name: update mysql root password for all root accounts
    sudo: yes
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
  - name: copy schema
    template: src=../resources/database/base.sql dest=/tmp/base.sql
  - name: create db
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: commute
      state: present
      target: /tmp/base.sql
  - name: create test db
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: test_commute
      state: present
      target: /tmp/base.sql
  - name: rm base.sql
    command: rm /tmp/base.sql
  - name: Install list of packages
    apt: name="{{item}}" state=installed
    with_items:
       - python3
       - python3-pip
       - cython
  - name: Install python3 packages
    command: pip3 install peewee pymysql

