require 'yaml'
Vagrant.configure('2') do |config|

  ## SSH Configuration
  config.ssh.username = 'jbremson'
  config.ssh.private_key_path = '~/.ssh/id_rsa'

   # Global Configuration
  config.vm.provider :linode do |provider, override|
    override.vm.box = 'linode'
    override.vm.box_url = "https://github.com/displague/vagrant-linode/raw/master/box/linode.box"
    linode_config = YAML::load_file('secret.yml')
    provider.token = linode_config["linode_key"]

    #Linode Settings
    provider.distribution = 'Ubuntu 14.04 LTS'
    provider.datacenter = 'fremont'
    provider.plan = '1024'
    provider.label = 'vagrant-ubuntu-lts'
  end
  # Shell Scripts
  config.vm.provision :shell, path: "setup.sh"

end